spring:
  datasource:
    url: jdbc:h2:mem:dt2025
    username: dt2025
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: localhost
    port: 5672
